theme: jekyll-theme-cayman
title: Nazarii Muzychuk
description: Software engineer
repository: nmuzychuk/nmuzychuk.github.io
google_analytics: UA-100998957-1

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
