theme: jekyll-theme-cayman
title: Nazarii Muzychuk
description: Software engineer
repository: nmuzychuk/nmuzychuk.github.io
google_analytics: UA-100998957-1

social:
  links:
    - https://www.linkedin.com/in/nazarii-muzychuk
    - https://www.youracclaim.com/user/nazarii-muzychuk
    - https://github.com/nmuzychuk

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
